### ISSUE TITLE
Problem: String is not a URI: [UriError]: Scheme is missing

### ISSUE THREAD

**Issue by bwjohnson-ss** [Mermade/openapi-lint-vscode#17] opened 2019-08-29 15:12 UTC
I'm editing an OpenAPI 3.0 spec in vscode and I believe that this extension is the source of validation problems. I've got several instances where I use `$ref` to reference a schema, but vscode reports this error:
```
              schema:
                $ref: '#/components/schemas/Account'
```
`String is not a URI: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: "/components/schemas/Account"}`

Any ideas on how to fix this?

**Comment by MikeRalphson** [comment] 2019-08-30 14:15
Can reproduce, but I wonder if error is coming from a built-in schema a new version of vscode / schema...

Actually it looks like the YAML extension has been taught about `openapi.yaml` files itself and is using a different schema.

See https://github.com/redhat-developer/vscode-yaml/issues/218

One workaround would be to use another supported name for your OAS file, such as `oas3,yaml` until the upstream YAML extension bug is fixed,

**Comment by ByteHunter** [comment] 2019-09-10 11:57
Can confirm. Renamed my openapi.yaml file to oas3.yaml and it worked like a charm.

**Comment by MikeRalphson** [comment] 2020-02-18 12:45
Should be fixed in `redhat.yaml` https://github.com/redhat-developer/vscode-yaml/releases/tag/0.7.2

**Closed by MikeRalphson** 2020-02-18 12:45 UTC
Labels: third-party-bug, workaround
